# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.2.1
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/frontend

    steps:
      - checkout
      - run: npm install
      - run: sudo apt-get update && sudo apt-get install -y python3 python3-pip
      - run: echo 'export PATH=$PATH:$HOME/.local/bin' >> $BASH_ENV
      - run: pip3 install --upgrade --user awscli
      # run tests!
      - run: npm test
      - run: npm run build
      - deploy:
          name: Deploy to S3 if tests pass and branch is Master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync build s3://cogrammers.community --delete
              aws configure set preview.cloudfront true
              aws cloudfront create-invalidation --distribution-id EXM4D7N8TGQBQ --paths '/*'

            else
              echo "Not master branch so not deploying"
            fi
